# iptables setup-Debian.yml
---
- name: Install iptables-persistent
  # apt: name=iptables-persistent state=present update_cache=yes cache_valid_time=3600
  apt: name=iptables-persistent state=present update_cache=yes
